```{r}
library(dados)
library(tidyverse)
```


```{r}
voos
```


```{r}
glimpse(voos)
```


```{r}
View(voos)
```


```{r}
voos |> 
  filter(destino == "IAH") |> 
  group_by(ano, mes, dia) |> 
  summarize(
    atraso_chegada = mean(atraso_chegada, na.rm = TRUE)
  )
```


```{r}
voos |> 
  filter(atraso_saida > 120)
```


```{r}
# Voos que partiram no dia 1 de Janeiro
voos |> 
  filter(mes == 1 & dia == 1)

# Voos que partiram em janeiro ou fevereiro
voos |> 
  filter(mes == 1 | mes == 2)
```


```{r}
# Uma forma mais curta e selecionar vôos que decolaram em janeiro ou fevereiro
voos |> 
  filter(mes %in% c(1, 2))
```


```{r}
jan1 <- voos |> 
  filter(mes == 1 & dia == 1)
```


```{r}
# Erros comuns usar "==" ao inves de "="
voos |> 
  filter(mes = 1)
```


```{r}
voos |> 
  filter(mes == 1 | 2)
```


```{r}
voos |> 
  arrange(ano, mes, dia, horario_saida)
```


```{r}
voos |> 
  arrange(desc(atraso_saida))
```


```{r}
# Remove linhas duplicadas, se existirem
voos |> 
  distinct()
```


```{r}
# Acha todos os pares únicos de origens e destinos
voos |> 
  distinct(origem, destino)
```


```{r}
voos |> 
  distinct(origem, destino, .keep_all = TRUE)
```


```{r}
voos |> 
  count(origem, destino, sort = TRUE)
```


```{r}
voos |> 
  mutate(
    tempo_ganho = atraso_saida - atraso_chegada,
    velocidade = distancia / tempo_voo * 60
  )
```


```{r}
voos |> 
  mutate(
    tempo_ganho = atraso_saida - atraso_chegada,
    velocidade = distancia / tempo_voo * 60,
    .before = 1
  )
```


```{r}
voos |> 
  mutate(
    tempo_ganho = atraso_saida - atraso_chegada,
    velocidade = distancia / tempo_voo * 60,
    .after = dia
  )
```


```{r}
voos |> 
  mutate(
    tempo_ganho = atraso_saida - atraso_chegada,
    horas = tempo_voo / 60,
    tempo_ganho_por_hora = tempo_ganho / horas,
    .keep = "used"
  )
```


```{r}
voos |> 
  select(ano, mes, dia)
```


```{r}
voos |> 
  select(ano:dia)
```


```{r}
voos |>
  select(!ano:dia)
```


```{r}
voos |> 
  select(where(is.character))
# starts_with("abc"): dá match em nomes que se iniciam com “abc”.
# ends_with("xyz"): dá match em nomes que terminam “xyz”.
# contains("ijk"): dá match em nomes que contém “ijk”.
# num_range("x", 1:3): buscará x1, x2 e x3.
```

```{r}
voos |> 
  rename(tail_num = codigo_cauda)
```


```{r}
voos |> 
  relocate(data_hora, tempo_voo)
```


```{r}
voos |> 
  relocate(ano:horario_saida, .after = data_hora)
voos |> 
  relocate(starts_with("cheg"), .before = horario_saida)
```


```{r}
voos |> 
  select(codigo_cauda) |> 
  arrange(atraso_chegada)
```


```{r}
# PIPE
voos |> 
  filter(destino == "IAH") |> 
  mutate(velocidade = distancia / tempo_voo * 60) |> 
  select(ano:dia, horario_saida, companhia_aerea, voo, velocidade) |> 
  arrange(desc(velocidade))
```


```{r}
arrange(
  select(
    mutate(
      filter(
        voos, 
        destino == "IAH"
      ),
      velocidade = distancia / tempo_voo * 60
    ),
    ano:dia, horario_saida, companhia_aerea, voo, velocidade
  ),
  desc(velocidade)
)
```


```{r}
voos1 <- filter(voos, destino == "IAH")
voos2 <- mutate(voos1, velocidade = distancia / tempo_voo * 60)
voos3 <- select(voos2, ano:dia, horario_saida, companhia_aerea, voo, velocidade)
arrange(voos3, desc(velocidade))
```


```{r}
voos |> 
  group_by(mes)
```


```{r}

```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

